import uuid
from datetime import datetime, date as date_type
from sqlalchemy import String, Boolean, Text, ForeignKey, DateTime, Date, Integer, Float, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID
from pgvector.sqlalchemy import Vector
from .database import Base

# Must match the output dimension of the embedding model (BAAI/bge-small-en-v1.5 = 384)
EMBEDDING_DIM = 384


class Community(Base):
    __tablename__ = "communities"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(100))
    description: Mapped[str | None] = mapped_column(Text)
    # centroid drifts toward the mean of all member embeddings as users join
    centroid: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM))
    # theme_embedding is computed once from the community name/description and stays stable
    theme_embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM))
    # None means the status is auto-computed; a non-None value overrides the algorithm
    status_override: Mapped[str | None] = mapped_column(String(20), nullable=True)
    location: Mapped[str | None] = mapped_column(String(100), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    members: Mapped[list["User"]] = relationship("User", back_populates="community")
    messages: Mapped[list["CommunityMessage"]] = relationship(
        "CommunityMessage", back_populates="community", cascade="all, delete-orphan", passive_deletes=True
    )


class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email: Mapped[str] = mapped_column(String, unique=True, index=True)
    username: Mapped[str] = mapped_column(String(50), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String)
    profile_summary: Mapped[str | None] = mapped_column(Text)   # Generated by Claude from onboarding chat
    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM))  # Embedding of profile_summary
    # community_id is the user's "primary" community pointer (legacy/convenience field);
    # actual membership is tracked in CommunityMembership to support multi-community users
    community_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("communities.id", ondelete="SET NULL"), nullable=True
    )
    onboarding_complete: Mapped[bool] = mapped_column(Boolean, default=False)
    is_digital: Mapped[bool] = mapped_column(Boolean, default=False)  # True = AI persona, not a real person
    is_admin: Mapped[bool] = mapped_column(Boolean, default=False)
    is_banned: Mapped[bool] = mapped_column(Boolean, default=False)   # Global platform ban
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    community: Mapped["Community | None"] = relationship("Community", back_populates="members")
    onboarding_messages: Mapped[list["OnboardingMessage"]] = relationship(
        "OnboardingMessage", back_populates="user", cascade="all, delete-orphan"
    )
    community_messages: Mapped[list["CommunityMessage"]] = relationship(
        "CommunityMessage", back_populates="user"
    )


class OnboardingMessage(Base):
    """Stores the full conversation between the user and the onboarding AI agent."""
    __tablename__ = "onboarding_messages"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"))
    role: Mapped[str] = mapped_column(String(20))   # "user" or "assistant"
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    user: Mapped["User"] = relationship("User", back_populates="onboarding_messages")


class CommunityMessage(Base):
    __tablename__ = "community_messages"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"))
    # CASCADE delete so community deletion removes all its messages atomically
    community_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("communities.id", ondelete="CASCADE")
    )
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    user: Mapped["User"] = relationship("User", back_populates="community_messages")
    community: Mapped["Community"] = relationship("Community", back_populates="messages")


class CommunityMembership(Base):
    """Junction table that supports a user belonging to multiple communities simultaneously."""
    __tablename__ = "community_memberships"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"))
    community_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("communities.id", ondelete="CASCADE"))
    joined_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    # Prevents the same user from appearing twice in one community
    __table_args__ = (UniqueConstraint("user_id", "community_id", name="uq_membership_user_community"),)


class CommunityBan(Base):
    """Permanent record of a user being kicked from a specific community."""
    __tablename__ = "community_bans"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"))
    community_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("communities.id", ondelete="CASCADE"))
    banned_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (UniqueConstraint("user_id", "community_id", name="uq_ban_user_community"),)


class CommunityAnnouncement(Base):
    """Stores event announcements fetched daily per community from external sources."""
    __tablename__ = "community_announcements"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    community_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("communities.id", ondelete="CASCADE"))
    title: Mapped[str] = mapped_column(Text)
    description: Mapped[str | None] = mapped_column(Text)
    event_url: Mapped[str | None] = mapped_column(Text)
    source: Mapped[str] = mapped_column(String(50))  # e.g. "Eventbrite", "Meetup", "Web"
    announced_date: Mapped[date_type] = mapped_column(Date, server_default=func.current_date())
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class CommunityWarning(Base):
    """Running tally of moderation warnings per user per community. Auto-bans at count >= 3."""
    __tablename__ = "community_warnings"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"))
    community_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("communities.id", ondelete="CASCADE"))
    count: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (UniqueConstraint("user_id", "community_id", name="uq_warning_user_community"),)


class DirectMessage(Base):
    __tablename__ = "direct_messages"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    sender_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"))
    receiver_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"))
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class AppLog(Base):
    """Application log records persisted to DB so the admin panel can display them."""
    __tablename__ = "app_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    time: Mapped[datetime] = mapped_column(DateTime, index=True)
    level: Mapped[str] = mapped_column(String(20))
    logger: Mapped[str] = mapped_column(String(100))
    message: Mapped[str] = mapped_column(Text)
    exc: Mapped[str | None] = mapped_column(Text)  # Formatted traceback, if any


class AgentMetricRecord(Base):
    """Per-call latency and error records for each AI agent, used by the metrics dashboard."""
    __tablename__ = "agent_metric_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    agent: Mapped[str] = mapped_column(String(100), index=True)
    latency_ms: Mapped[float] = mapped_column(Float)
    error: Mapped[bool] = mapped_column(Boolean, default=False)
    tool_calls: Mapped[int] = mapped_column(Integer, default=0)
    recorded_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), index=True)
